-- MySQL Script generated by MySQL Workbench
-- Fri Apr 27 04:19:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Messaging
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Messaging` ;

-- -----------------------------------------------------
-- Schema Messaging
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Messaging` ;
USE `Messaging` ;

-- -----------------------------------------------------
-- Table `Messaging`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Messaging`.`roles` ;

CREATE TABLE IF NOT EXISTS `Messaging`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Messaging`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Messaging`.`users` ;

CREATE TABLE IF NOT EXISTS `Messaging`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `roleID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `roleID_idx` (`roleID` ASC),
  CONSTRAINT `roleID`
    FOREIGN KEY (`roleID`)
    REFERENCES `Messaging`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Messaging`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Messaging`.`messages` ;

CREATE TABLE IF NOT EXISTS `Messaging`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `senderID` INT NULL DEFAULT NULL,
  `receiverID` INT NULL DEFAULT NULL,
  `subm_date` DATE NULL DEFAULT NULL,
  `msg_body` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `senderID_idx` (`senderID` ASC),
  INDEX `receiverID_idx` (`receiverID` ASC),
  CONSTRAINT `senderID`
    FOREIGN KEY (`senderID`)
    REFERENCES `Messaging`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiverID`
    FOREIGN KEY (`receiverID`)
    REFERENCES `Messaging`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Messaging`.`actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Messaging`.`actions` ;

CREATE TABLE IF NOT EXISTS `Messaging`.`actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Messaging`.`rights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Messaging`.`rights` ;

CREATE TABLE IF NOT EXISTS `Messaging`.`rights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `roleID` INT NULL DEFAULT NULL,
  `actionID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
